/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CaseStudyRouteImport } from './routes/case-study'
import { Route as CapacityRouteImport } from './routes/capacity'
import { Route as IndexRouteImport } from './routes/index'

const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyRoute = CaseStudyRouteImport.update({
  id: '/case-study',
  path: '/case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityRoute = CapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capacity': typeof CapacityRoute
  '/case-study': typeof CaseStudyRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/inventory': typeof InventoryRoute
  '/purchasing': typeof PurchasingRoute
  '/risk': typeof RiskRoute
  '/scenarios': typeof ScenariosRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capacity': typeof CapacityRoute
  '/case-study': typeof CaseStudyRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/inventory': typeof InventoryRoute
  '/purchasing': typeof PurchasingRoute
  '/risk': typeof RiskRoute
  '/scenarios': typeof ScenariosRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capacity': typeof CapacityRoute
  '/case-study': typeof CaseStudyRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/inventory': typeof InventoryRoute
  '/purchasing': typeof PurchasingRoute
  '/risk': typeof RiskRoute
  '/scenarios': typeof ScenariosRoute
  '/twin': typeof TwinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capacity'
    | '/case-study'
    | '/dashboard'
    | '/forecast'
    | '/inventory'
    | '/purchasing'
    | '/risk'
    | '/scenarios'
    | '/twin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capacity'
    | '/case-study'
    | '/dashboard'
    | '/forecast'
    | '/inventory'
    | '/purchasing'
    | '/risk'
    | '/scenarios'
    | '/twin'
  id:
    | '__root__'
    | '/'
    | '/capacity'
    | '/case-study'
    | '/dashboard'
    | '/forecast'
    | '/inventory'
    | '/purchasing'
    | '/risk'
    | '/scenarios'
    | '/twin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapacityRoute: typeof CapacityRoute
  CaseStudyRoute: typeof CaseStudyRoute
  DashboardRoute: typeof DashboardRoute
  ForecastRoute: typeof ForecastRoute
  InventoryRoute: typeof InventoryRoute
  PurchasingRoute: typeof PurchasingRoute
  RiskRoute: typeof RiskRoute
  ScenariosRoute: typeof ScenariosRoute
  TwinRoute: typeof TwinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study': {
      id: '/case-study'
      path: '/case-study'
      fullPath: '/case-study'
      preLoaderRoute: typeof CaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity': {
      id: '/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof CapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapacityRoute: CapacityRoute,
  CaseStudyRoute: CaseStudyRoute,
  DashboardRoute: DashboardRoute,
  ForecastRoute: ForecastRoute,
  InventoryRoute: InventoryRoute,
  PurchasingRoute: PurchasingRoute,
  RiskRoute: RiskRoute,
  ScenariosRoute: ScenariosRoute,
  TwinRoute: TwinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
